spring:
  application:
    name: Sports-Quiz

quiz:
  dynamo:
    enabled: false
    endpoint: http://localhost:8000
    region: us-east-1
    teams-table-name: sports-quiz-teams
    results-table-name: sports-quiz-results
    seed: false
